{'dateCreated': <DateTime '20200409T02:25:00' at 0x1a4f2528408>, 'description': '测试的时候用的Django是2.0.9的版本，python3.7，结果怎么改都会出问题，在stackoverflow发现竟然是sqlite的版本问题，需要降级到2.6之前的版本，怎么降级sqlite没找到，还好Django在2.1.5修复了这个bug， https://code.djangoproject.com/ticket/29182。\n所以就升级一下Django吧，2.1.5之后就没问题了\n\n\n```\npip install Django==2.1.5\n```', 'title': 'django.db.utils.OperationalError: no such table: main.auth_user__old', 'categories': ['[随笔分类]Python~Django'], 'enclosure': {'length': 0}, 'link': 'https://www.cnblogs.com/wbyixx/p/12664225.html', 'permalink': 'https://www.cnblogs.com/wbyixx/p/12664225.html', 'postid': '12664225', 'source': {}, 'userid': '-2'}